### ISSUE TITLE
Why the tests SQLite databases aren't stored in the Laravel's storage folder?

### ISSUE THREAD

**Issue by xel1045** [eXolnet/LaravelModule#29]

**Comment by tomzx** [comment]
Which database are we talking about here?

AFAIK, you configure where you want the databases to be created in the `config/database.php` folder in laravel 5.

**Comment by tomzx** [comment]
If you look at https://github.com/laravel/laravel/tree/v4.2.11/app/database, you'll see that `production.sqlite` used to be in the `database` folder (laravel 4.2).

Nowadays (laravel 5), there's no `production.sqlite` file, thus I guess it doesn't matter where it's created. Furthermore, it is configurable through the `config/database.php` or the environment file, but in a development environment, I wouldn't suggest touching it as it will break automated tests, which in hindsight, is possibly an issue.

Finally, note that wherever the `sqlite` folder is moved to, it'll need to have a `.gitignore` in it as the code does not create the folder if it does not exist (I think we should create the path if it is missing).
